### ISSUE TITLE
The 3 columns quite confusing

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#174]
**Please describe the problem**
I'm confused with the relationship between the 3 columns.

**Describe the improvement you'd like to suggest**
You need to have column titles! That would help greatly!

**Additional context**
Very colourful but I get confused

<hr>

**Reported by:** @matthiaslum
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#30]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback! 

The suggestion you made is what we planned to do for the upcoming v1.4 milestone :)
