### ISSUE TITLE
Select function not working as described in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#176]
**Describe the bug**
Select function just selects the bug but does not load google page as per described in user guide

**To Reproduce**
1. Select 'index'
2. See error

**Expected behavior**
A google search page of the selected name should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/35647582/55453232-a851af80-560d-11e9-97d3-9baafa1cf54c.png)

**Additional context**

<hr>

**Reported by:** @shengkok
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#38]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback.
The User Guide was already updated after v1.3 release to fix this issue.
