### ISSUE TITLE
Help should not point me to the user guide

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#177]
The help needs to be more concise, just give the examples of the commands to run, not the user guide. sorry!

<hr>

**Reported by:** @matthiaslum
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#41]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback!

This is the intended behaviour. If the user needs help, the User Guide is provided as a reference.
Providing a small list of examples commands that users can try may prove to be helpful, but yet they may confuse new users who do not understand how to use the application further.

As such, linking them to the User Guide aims to help provide a more comprehensive list of the usage of all commands.
