### ISSUE TITLE
History command does not work as expected

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#178]
**Describe the bug**
The history command works but the list shown is not ordered correctly as stated.

**To Reproduce**
Type in few valid commands and execute the history command.

**Expected behavior**
An ordered list of commands from "(from most recent to earliest)", instead it is ordered by lexicographical order.

<hr>

**Reported by:** @seanieyap
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#58]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback.
We will update and fix the history command accordingly.
