### ISSUE TITLE
Modules with same name can be added

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#180]
**Describe the bug**
I can add modules with the same name but different code.

**To Reproduce**
1. Go to UI
2. type:
add code/CS1010 name/Programming Methodology credits/4 tag/programming tag/algorithms tag/c tag/imperative

add code/CS2323 name/Programming Methodology credits/4 tag/programming tag/algorithms tag/c tag/imperative

**Expected behavior**
If either the code is the same or the name is the same as any other module, it should throw an error. It does not make sense to have different code but same module name. Its like having CS2113T Software Engineering and CS3333 Software Engineering. Sorry for being so picky

**Screenshots**
<img width="281" alt="Screen Shot 2019-04-03 at 12 50 09 PM" src="https://user-images.githubusercontent.com/43682311/55453656-514cda00-560f-11e9-9b4b-ccfcc66eb761.png">

**Additional context**

<hr>

**Reported by:** @matthiaslum
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#88]</sub>

**Comment by Creastery** [comment]
This is the intended behaviour. There are modules with the same name but different code.
One such example is CS2113T Software Engineering & Object-Oriented Programming and CS2103T Software Engineering & Object-Oriented Programming.

Nonetheless, thanks for the feedback!
