### ISSUE TITLE
Add command Bug

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#181]
**Describe the bug**
Cannot add documentation "add" command example

**Expected behavior**
Add the entry

**Screenshots**
![asd](https://user-images.githubusercontent.com/33095662/55453707-8a854a00-560f-11e9-8d35-58f422a9c627.PNG)

**Additional context**

<hr>

**Reported by:** @frankquekch
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#93]</sub>

**Comment by Creastery** [comment]
This was already fixed. Nonetheless, thanks for spotting it.
