### ISSUE TITLE
Command "Quick Start" in user guide does not work

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#183]
**Describe the bug**
Under the section "Quick Start", bullet 6, it tells the user to perform the following command, "add name/Programming Methodology code/CS1010", but this command is invalid.

**To Reproduce**
Execute command "add name/Programming Methodology code/CS1010".

**Expected behavior**
Command will be invalid instead of valid.

<hr>

**Reported by:** @seanieyap
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#132]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback. 
The User Guide was already updated after v1.3 release to fix this issue.
