### ISSUE TITLE
Amount to credits allowed to be allocated to a module is unrealistic

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#184]
Just a suggestion:

setting the upper bound for the amount of credits that a module can have to 999 seems unrealistic, perhaps 20 would suffice.

<hr>

**Reported by:** @seanieyap
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#150]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback. 

We intend to refine it further, but currently the upper bound for `Credits` of 999 is set as a symbolic move.
