### ISSUE TITLE
Selecting Module does not load the google search page

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#185]
**Please describe the problem**
The user guide says that selecting a module will load the google search page for that module.
But no google search page appears when I select the module.

**Describe the improvement you'd like to suggest**
Change the documentation, or make the select more useful.

**Additional context**
<img width="1092" alt="Screen Shot 2019-04-03 at 1 09 29 PM" src="https://user-images.githubusercontent.com/43682311/55454241-c02b3280-5611-11e9-8957-369d2a0fc379.png">

<hr>

**Reported by:** @matthiaslum
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#153]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback.
The User Guide was already updated after v1.3 release to fix this issue.

**Comment by Creastery** [comment]
Duplicate of #176
