### ISSUE TITLE
Difference between list and planner_list_all

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#186]
**Describe the bug**
Difference between the 2 

**Expected behavior**
Both seems to produce the same results

**Additional context**

<hr>

**Reported by:** @frankquekch
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#159]</sub>

**Comment by Creastery** [comment]
As mentioned in the User Guide, `planner_list` command is not implemented yet (coming in v2.0).
Nonetheless, thanks for the feedback.
