### ISSUE TITLE
Invalid example in User guide related to name of requirement

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#187]
**Describe the bug**
The following example in the User guide has a type such that it gives invalid "degree requirement category":

"requirement_add name/Computing Foundations code/CS1231 code/CS2100 Adds modules CS1231 and CS2100 into Computing Foundations degree requirement category."

**To Reproduce**
1. Execute command "requirement_add name/Computing Foundations code/CS1231 code/CS2100".

<hr>

**Reported by:** @seanieyap
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#187]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback.
The User Guide was already updated after v1.3 release to fix this issue.
