### ISSUE TITLE
Developer documentation and program command not in sync 

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#188]
**Describe the bug**
Above statement

**Expected behavior**

**Screenshots**
Program
![Capture](https://user-images.githubusercontent.com/33095662/55454490-ae965a80-5612-11e9-88e4-b466a141a550.PNG)
UG
![asd](https://user-images.githubusercontent.com/33095662/55454513-c077fd80-5612-11e9-9476-56017badf2ff.PNG)

**Additional context**

<hr>

**Reported by:** @frankquekch
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#198]</sub>

**Comment by Creastery** [comment]
As mentioned in the User Guide, `planner_list` command is not implemented yet (coming in v2.0).
Nonetheless, thanks for the feedback.
