### ISSUE TITLE
Name of requirement is case sensitive which is not consistent with code

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#189]
**Describe the bug**
name of requirement is case sensitive which is not stated in user guide and not consistent with CODE parameters(not case sensitive) used in the same command.

**To Reproduce**
1. requirement_add name/computing breadth code/...

**Expected behavior**
code should be added inside the requirement.

**Screenshots**

**Additional context**

<hr>

**Reported by:** @shengkok
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#207]</sub>

**Comment by Creastery** [comment]
Thanks for the feedback.

This is the intended behaviour as of v1.3 milestone. It is in the roadmap to make `Name` case-insensitive as part of v1.4 milestone.

**Comment by Creastery** [comment]
Duplicate of #163
