### ISSUE TITLE
Combine VersionedDegreePlannerList into VersionedAddressBook

### ISSUE THREAD

**Issue by Letm3through** [CS2113-AY1819S2-T09-1/main#97]
In the current implementation, `DegreePlanner` class has its own `VersionedDegreePlannerList` class.
This has to be modified to combine with `VersionedAddressBook` along with the storage for `DegreePlanner` to integrate into that of `AddressBook` so that it would be make the application flow and architecture more logical.

**Comment by Creastery** [comment]
Closed in view of PR #75.

**Comment by truegitnovice** [comment]
Closed in view of merged PR #75 .
